config/routes.rb
Charthub::Application.routes.draw do

  devise_for :users

  scope '/:login/' do
    match 'series' => 'members#series', :as => :login_series
    match 'series/:id' => 'series#show', :as => :login_series_show
    match 'series/:id/load' => 'series#load', :as => :login_series_load
    match 'tables' => 'members#series_collections', :as => :login_series_collections
    match 'tables/:id' => 'series_collections#show', :as => :login_series_collection_show
    match 'tables/:id/load' => 'series_collections#load', :as => :login_series_collections_load
    match 'graphs' => 'members#graphs', :as => :login_graphs
    match 'graphs/:id' => 'graphs#show', :as => :login_graph_show
    match 'graphs/:id/load' => 'graphs#load', :as => :login_graph_load
  end
  match 'series/:id/load' => 'series#load', :as => :series_load
  match 'series/:id/desc' => 'series#get_desc', :as => :series_get_desc, :via => :get
  match 'series/preview' => 'series#preview_values', :as => :series_preview_values, :via => :post
  match 'series/:id/values' => 'series#create_values', :as => :series_create_values, :via => :post
  match 'tables/:id/load' => 'series_collections#load', :as => :series_collections_load
  match 'tables/:id/desc' => 'series_collections#get_desc', :as => :series_collections_get_desc, :via => :get
  match 'graphs/:id/load' => 'graphs#load', :as => :graph_load
  match 'graphs/config_test_new' => 'graphs#config_test_new', :as => :graph_config_test_new, :via => :put
  match 'graphs/:id/config_test_edit' => 'graphs#config_test_edit', :as => :graph_config_test_edit, :via => :put
  match 'graphs/new_memo' => 'graphs#new_memo', :as => :graph_new_memo
  match 'graphs/:id/image' => 'graphs#image', :as => :graph_image
  match 'profile/edit' => 'profiles#edit_myself'
  match 'profile/update' => 'profiles#update_myself', :via => :put
  match 'series/:series_id/graphs/new' => 'graphs#new_for_series', :as => :series_graphs_new
  match 'tables/:series_collection_id/graphs/new' => 'graphs#new_for_series_collection', :as => :series_collection_graphs_new
  match 'tables/:id/series' => 'series_collections#get_series', :via => :get
  match 'tables/:id/collection' => 'series_collections#get_selected_rows', :as => 'series_collection_collection', :via => :get
  match 'tables/:id/collection' => 'series_collections#update_collection', :as => 'update_series_collection_collection', :via => :put
  match 'config/index' => 'config#index', :as => 'config_index', :via => :get

  resources :series do
    resources :values
  end
  resources :profiles
  resources :series_orders
  resources :series_collections, :path => '/tables'
  resources :series_filters
  resources :graphs

  match '/home' => 'home#show', :as => :login_home
  match ':login/' => 'members#show', :as => :login_member_home

  root :to => 'top#index'

end

app/models/series_collection.rb
# -*- coding: utf-8 -*-
class SeriesCollection < ActiveRecord::Base
  attr_accessible :description, :name, :user_id, :locked

  has_many :series_orders, dependent: :delete_all
  has_many :series, :through => :series_orders
  belongs_to :user, counter_cache: :series_collections_count

  has_many :graphs, :as => :graphable, dependent: :delete_all

  has_many :series_calculators, dependent: :delete_all

  def to_json_for_chart
    return self.series_table.to_json_for_chart
  end

  def to_json_for_chart_with_option(op)
    return self.series_table.to_json_for_chart_with_option(op)
  end

  # HTMLテーブルのソースとなるデータに整形。
  def series_table
    return self.temporary_table
  end

  def series_table_with_view_options(op)
    return self.temporary_table_with_view_options(op)
  end

  # 様々な形式に変換するための一時テーブル
  def temporary_table

    temp_table = MyLib::MyTemporaryTableFactory.new
    temp_table.series_collection = self
    temp_table.series_orders = self.series_orders
    temp_table.series_calculators = self.series_calculators
    return temp_table.eval

    #return temp_table

  end

  def temporary_table_with_view_options(op)

    temp_table = MyLib::MyTemporaryTableFactory.new
    temp_table.series_collection = self
    temp_table.series_orders = self.series_orders
    temp_table.series_calculators = self.series_calculators
    temp_table.view_options = op
    return temp_table.eval

    #return temp_table

  end

  # 実系列と計算系列のソースを合わせた配列を作成する。
  def sources

    sources = Array.new

    # 実系列のヘッダー情報を収集する。
    self.series_orders.each{|order|
      sources << order
    }
    # 計算系列のヘッダー情報を収集する。
    self.series_calculators.each{|culc|
      sources << culc
    }

    sources.sort!{|a, b|
      a.sequence <=> b.sequence
    }

    return sources

  end

  # 紐付く系列のグラフを取得
  def child_graphs
    graphs_tmp = Array.new
    self.series_orders.each{|order|
      # テーブルに含まれる系列自身に紐づくグラフを取得
      order.series_with_deleted.graphs.each{|graph|
        # 重複したグラフは排除する
        duplicate_fg = false
        graphs_tmp.each{|g|
          if g.id == graph.id
            duplicate_fg = true
          end
        }
        if !duplicate_fg
          graphs_tmp.push(graph)
        end
      }

      # テーブルに含まれる系列の先祖系列に紐づくグラフを取得
      #graphs_tmp +=  order.series_with_deleted.child_graphs
      order.series_with_deleted.child_graphs.each{|graph|
        # 重複したグラフは排除する
        duplicate_fg = false
        graphs_tmp.each{|g|
          if g.id == graph.id
            duplicate_fg = true
          end
        }
        if !duplicate_fg
          graphs_tmp.push(graph)
        end
      }

    }
    return graphs_tmp
  end

  # 系列コレクションに紐付いた全ての(実系列|計算系列)についてグラフ用オプションの配列を作成。
  # グラフを新規作成する際はこれが空の設定となり、グラフを編集する際にはここで生成した
  # オプションを保存した設定で上書きする。
  def get_all_series_options

    all_series = self.sources

    series_options = MyLib::MySeriesOptions.new
    i=0
    all_series.each{|series|
      case series.class.name 
      when "Series","SeriesCalculator"
        # MEMO: "Series"はseries_collectionの中では発生しないはず。
        #       （graphモデルの中で処理していたときの名残）
        series_tmp = MyLib::MySeriesOption.new
        series_tmp.series_class = series.class.name
        series_tmp.series_type = series.class.name
        series_tmp.series_id = series.id
        series_tmp.name = series.name
      when "SeriesOrder"
        # 系列コレクションに紐付く系列の場合、IDは実系列のID、名前はorderに設定されたエイリアス
        # または実系列の名前から取得。
        series_tmp = MyLib::MySeriesOption.new
        series_tmp.series_class = "Series"
        series_tmp.series_type = series.class.name
        series_tmp.series_id = series.series.id
        series_tmp.name = series.name
      end
      series_tmp.color_template = CHART_CONFIG[:colorSet][i]
      series_options << series_tmp
      i+=1
      i=0 if i >= CHART_CONFIG[:colorSet].size
      
    }

    return series_options

  end

  # 項目軸の種別を返す。
  # 紐付く系列は全て同じ項目軸種別なので、最初の系列のそれを返す。
  # まだ系列が一つも紐付けられていない状態もありうるため、その場合は
  # nilを返す。
  def category_axis_type
    if self.series_orders[0].nil?
      return nil
    else
      return self.series_orders[0].series.category_axis_type
    end
  end

  def category_axis_is_sortable?
    ['date_y', 'date_ym', 'date_ymd', 'integer'].include?(self.category_axis_type)
  end

  def category_axis_is_date?
    ['date_y', 'date_ym', 'date_ymd'].include?(self.category_axis_type)
  end

  def category_axis_type_label
    MY_APP['category_axis_type_label'][self.category_axis_type]
  end

end

app/controllers/series_collections_controller.rb
# -*- coding: utf-8 -*-
class SeriesCollectionsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show, :load]
  before_filter :check_permission, except: [:index, :show, :new, :create, :load, :get_desc, :get_series, :get_selected_rows]

  # GET /series_collections
  # GET /series_collections.json
  def index
    #@series_collections = SeriesCollection.all(:include => [:user])
    @series_collections = Kaminari.paginate_array(SeriesCollection.includes(:user).order('updated_at DESC'))
    @series_collections = @series_collections.page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @series_collections }
    end
  end

  # GET /series_collections/1
  # GET /series_collections/1.json
  def show
    @series_collection = SeriesCollection.find(params[:id])
    @series_table = @series_collection.series_table
    @sources = @series_collection.sources

   # TODO: 2014-10-15 使われておらず不要と思われるので削除。
   # @graph_config = CHART_CONFIG #グラフパラメータの初期値を設定。
   # @graph_config[:title] = @series_collection.name

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @series_collection }
    end
  end

  # GET /series_collections/new
  # GET /series_collections/new.json
  def new
    @series_collection = SeriesCollection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @series_collection }
    end
  end

  # GET /series_collections/1/edit
  def edit
    #@series_collection = SeriesCollection.find(params[:id])
  end

  # POST /series_collections
  # POST /series_collections.json
  def create
    @series_collection = SeriesCollection.new(params[:series_collection])
    @series_collection.user_id = current_user.id

    respond_to do |format|
      if @series_collection.save
        format.html { redirect_to @series_collection, notice: 'Table was successfully created.' }
        format.json { render json: @series_collection, status: :created, location: @series_collection }
      else
        format.html { render action: "new" }
        format.json { render json: @series_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /series_collections/1
  # PUT /series_collections/1.json
  def update
    #@series_collection = SeriesCollection.find(params[:id])

    respond_to do |format|
      if @series_collection.update_attributes(params[:series_collection])
        format.html { redirect_to @series_collection, notice: 'Table was successfully updated.' }
        #format.json { head :no_content }
        format.json { render json: @series_collection, status: :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @series_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series_collections/1
  # DELETE /series_collections/1.json
  def destroy
    #@series_collection = SeriesCollection.find(params[:id])
    login = @series_collection.user.login
    @series_collection.series_orders.clear
    @series_collection.series_calculators.clear
    @series_collection.graphs.clear
    @series_collection.destroy

    respond_to do |format|
      #format.html { redirect_to series_collections_url }
      format.html { redirect_to login_home_path }
      format.json { head :no_content }
    end
  end

  def load

    @series_collection = SeriesCollection.find(params[:id])
    series_table = @series_collection.series_table

    # デフォルト値をセット
    @graph_config = Hash.new
    @graph_config = MyLib::MyCcchartConfig.default_to_chart
    @graph_config[:title] = @series_collection.name

    #render json: {data: @series_collections.to_json_for_chart, config: @graph_config, status: 200}
    render json: {data: series_table.to_json_for_chart, config: @graph_config, status: 200}

  end

  def get_series

    series_collection = SeriesCollection.find(params[:id])

    respond_to do |format|
      format.json { render json: series_collection.series_orders.to_json(:include => [:series]) }
    end

  end

  # 系列の選択ボックスで、コレクションとして選択されている
  # 系列を全て取得する。
  # 実体のある系列と計算系列を別々に取得してsequenceでソート
  # してから返却する。
  def get_selected_rows

    series_collection = SeriesCollection.find(params[:id])

    arr = Array.new

    # 系列を取得してハッシュに追加。
    series_collection.series_orders.each{|order|
      arr.push({
        row_type: 'series',
        sequence: order.sequence,
        series_order_id: order.id, 
        series_id: order.series_id, 
        name: order.series_with_deleted.name,
        alias: order.alias,
        category_axis_type: order.series_with_deleted.category_axis_type
      })
    }

    # 計算系列を取得してハッシュに追加。
    series_collection.series_calculators.each{|culc|
      arr.push({
        row_type: 'series_calculator',
        sequence: culc.sequence,
        series_calculator_id: culc.id, 
        name: culc.name,
        expression: culc.expression
      })
    }

    arr.sort!{|a, b|
      a[:sequence] <=> b[:sequence]
    }

    respond_to do |format|
      format.json { render json: arr.to_json }
    end

  end

  # 選択された系列から、
  # 実体のある系列（series）と実体を持たない計算系列（series_calculator)
  # の2種類の情報を受け取り、それぞれをDBに登録する。
  def update_collection

    #series_collection = SeriesCollection.find(params[:id])
    series_collection = @series_collection

    SeriesCollection.transaction do

    # 既存の情報を削除
    series_collection.series_orders.destroy_all
    #series_collection.series_calculators.destroy_all

    # 受け取った系列と計算系列の順序を記録する。
    # これによって、系列と計算系列を別々にDBからselectした後で並び替える事ができる。
    params_series_order = Array.new
    #params_series_calculator = Array.new
    create_tmp = Array.new
    update_tmp = Array.new
    params[:collection].each_with_index{|col, i|
      case col[:row_type]
      when 'series'
        params_series_order.push({
          series_id: col[:series_id],
          sequence: i,
          alias: col[:alias]
        })
      when 'series_calculator'
        mode_tmp = col[:series_calculator_id].blank? ? 'new' : 'update'
        case mode_tmp
        when 'new'
          create_tmp.push({
            name: col[:name],
            sequence: i,
            expression: col[:expression]
          })
        when 'update'
          update_tmp.push({
            id: col[:series_calculator_id].to_i,
            name: col[:name],
            sequence: i,
            expression: col[:expression]
          })
        end
      end
    }

    check_selected_series(params_series_order)

    # 実体系列
    if params_series_order.size > 0
      series_orders = series_collection.series_orders.build(params_series_order)
      series_orders.each{|series_order|
        series_order.save!
      }
    end

    # 計算系列
      # 削除
      destroy_ids = []
      series_collection.series_calculator_ids.each{|id|
        fg = false
        update_tmp.each{|culc|
          if id == culc[:id]
            fg = true
          end
        }
        destroy_ids << id unless fg
      }
      SeriesCalculator.destroy(destroy_ids) if destroy_ids.size > 0

      # 新規,更新
      #新規
      if create_tmp.size > 0
        series_calculators = series_collection.series_calculators.build(create_tmp)
        series_calculators.each{|culc| culc.save! }
      end 

      #更新
      update_tmp.each{|culc|
        # UPD: 2014-10-16 元のテーブルに紐付いた計算系列であるかをここでチェック
        #      悪意のあるリクエストにより異なるテーブルに紐付いた計算系列をアップデートされないため。
        series_calculator = SeriesCalculator.find(culc[:id])
        if series_calculator.series_collection_id == series_collection.id
          series_calculator.attributes = culc
          series_calculator.save!
        end
      }

      series_collection.updated_at = Time.now
      series_collection.save!

    end #transaction

    respond_to do |format|
      format.json { render json: {notice: 'Table was successfully updated.'}}
    end

  rescue MyLib::MyInvalidSeriesSelectedException => e
    respond_to do |format|
      format.json { render json: {notice: e.message}}
    end
  end

  def get_desc

    series = SeriesCollection.find(params[:id])
    renderd = view_context.safe_text(series.description)

    render text: renderd

  end

private
  def check_selected_series(params_orders)
    series = Array.new
    params_orders.each{|order|
      begin
        series.push( Series.find(order[:series_id]) )
      rescue ActiveRecord::RecordNotFound => e
        raise MyLib::MyInvalidSeriesSelectedException.exception("存在しない系列が含まれています。")
      end
    }

    series_tmp = nil
    series.each_with_index{|s, i|
      if i == 0 
        series_tmp = s
      else
        if series_tmp.category_axis_type != s.category_axis_type
          raise MyLib::MyInvalidSeriesSelectedException.exception("異なる種別の項目ラベルが混在しています。")
        end
        series_tmp = s
      end 
    }

    series_ids = Array.new
    series.each{|s|
      if series_ids.include?(s.id)
        raise MyLib::MyInvalidSeriesSelectedException.exception("同じ系列が重複しています。")
      else
        series_ids.push(s.id)
      end
    }
  end
end

app/helpers/series_collections_helper.rb
module SeriesCollectionsHelper
end

app/views/series_collections/_form.html.erb
<%= form_for(@series_collection, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @series_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series_collection.errors.count, "error") %> prohibited this series_collection from being saved:</h2>

      <ul>
      <% @series_collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if false -%>
  <div class="control-group">
    <%= f.label :id, :class => "control-label" %>
    <div class="controls">
    <%= @series_collection.id %>
    </div>
  </div>
<% end -%>
  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :name %>
    </div>
  </div>
<% if false -%>
  <div class="control-group">
    <%= f.label :locked, :class => "control-label" %>
    <div class="controls">
    <%= f.check_box :locked %>
    </div>
  </div>
<% end -%>
  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
    <%= f.text_area :description, :rows => 10 %>
    </div>
  </div>
  <div class="actions control-group">
    <div class="controls">
    <%= f.submit class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/series_collections/_index_row.html.erb
  <tr>
    <td>
      <%= link_to index_row.user.profile.name_view, login_member_home_path(login: index_row.user.login) %>
    </td>
    <td>
      <%= link_to index_row.name, login_series_collection_show_path(login: index_row.user.login, id: index_row.id) %>
    </td>
    <td><%= l index_row.updated_at, format: :short %></td>
  </tr>

app/views/series_collections/_selector.html.erb
<% if signed_in_and_yours?(series.user_id) -%>
<ul class="nav nav-tabs">
  <li id="edit_collections" class="active">
    <a>編集</a>
  </li>
</ul><!-- nav-tabs -->
<%#= button_tag '編集', :id => 'edit_collections', :class => 'btn', :type => 'button' %>
<% end #if -%>

<div id="series_select_area" class="well well-small">
<div class="controls_row">
<div class="pull-right">
<%= button_tag '閉じる', :id => 'close_selector', :class => 'btn', :type => 'button' %>
</div><!-- pull-right -->
</div><!-- controls_row -->

<p class="dialog_h1">系列の追加・削除</p>

<p class="dialog_h2">追加する系列</p>
<div class="dialog_group">
  <div class="input-append">
    <%= text_field_tag :search_query, '', :id => :search_query %>
    <button id="search_series" type="button" class="btn">検索</button>
  </div>
  (<span id="count_series"></span> series found)
<div id="source_series_area" class="controls_row">
<table id="source_series" class="table table-condensed">
</table>
<%= hidden_field_tag :selected_series_id, '', :id => :selected_series_id %>
</div><!-- source_series_area -->

<%= button_tag raw('<i class="icon-plus"></i> 追加'), :id => :add_series, :class => 'btn' %>
</div><!-- dialog_group -->

<% if series_type == 'series_collection' -%>
  <%= render :partial => 'series_collections/series_for_collection', :locals => {:series_collection => series} -%>
<% end -%>


</div><!-- series_select_area -->

<%= hidden_field_tag :login_name, series.user.login, :id => 'login_name' %>
<%= hidden_field_tag :series_type, series_type, :id => 'series_type' %>
<% if series_type == 'series_collection' -%>
<%= hidden_field_tag :series_collection_id, series.id, :id => 'series_collection_id' %>
<% end #if -%>

<% #以下テンプレート -%>
<script id="source_series_template" type="text/x-jquery-tmpl">
<tr id="${series_id}" class="select_table_row" onclick="selectSeriesRow(this)">
<td class="width80"><div class="label label-info" title="${axis_type_label}">${axis_type}</div></td>
<td>${name}</td>
</tr>
</script>

<script id="selected_series_template" type="text/x-jquery-tmpl">
<tr class="select_table_row" onclick="selectCollectionRow(this)">
<td style="width:50px;"><%= button_tag '削除', :class => 'btn btn-mini btn-danger', :onclick => "removeSelectedSeries(this)", :type => :button %> </td>
<td style="width:20px;">${no}</td>
<td class="width80"><div class="label label-info" title="${axis_type_label}">${axis_type}</div></td>
<td class="name">${name}</td>
<td class="alias">${alias}</td>
<td>
<%= hidden_field_tag 'collection[][row_type]', 'series' %>
<%= hidden_field_tag 'collection[][series_order_id]', '${series_order_id}' %>
<%= hidden_field_tag 'collection[][series_id]', '${series_id}' %>
<%= hidden_field_tag 'collection[][alias]', '${alias}', :class => 'alias' %>
</td>
</tr>
</script>

<script id="selected_series_template_for_calculator" type="text/x-jquery-tmpl">
<tr class="select_table_row" onclick="selectCollectionRowCulc(this)">
<td style="width:50px;"><%= button_tag '削除', :class => 'btn btn-mini btn-danger', :onclick => "removeSelectedSeries(this)", :type => :button %> </td>
<td style="width:20px;">${no}</td>
<td class="width80"></td>
<td class="name">${name}</td>
<td class="expression">${expression}</td>
<td>
<%= hidden_field_tag 'collection[][row_type]', 'series_calculator' %>
<%= hidden_field_tag 'collection[][series_calculator_id]', '${series_calculator_id}' %>
<%= hidden_field_tag 'collection[][name]', '${name}', :class => 'name' %>
<%= hidden_field_tag 'collection[][expression]', '${expression}', :class => 'expression' %>
</td>
</tr>
</script>

app/views/series_collections/_series_for_collection.html.erb
<p class="dialog_h2">追加された系列</p>
<div class="dialog_group">

<%= form_tag(series_collection_collection_path(id: series_collection.id), :id => :edit_collection_form, :remote => true, :method => :put) do -%>

<div id="selected_series_area">
<table id="selected_series" class="table table-condensed">
</table>
</div><!-- selected_series_area -->

<div id="series_alias" class="control-box">
系列の別名
<div class="input-append">
<%= text_field_tag :series_name_alias, '' %><%= button_tag '更新', :type => :button, :id => :update_alias, :class => "btn" %>
</div>
</div><!-- edit_series -->

<div id="series_calculator_properties" class="control-box">
名前<%= text_field_tag :series_calculator_name, '' %>
式<%= text_field_tag :series_calculator_expression, '' %>
<%= button_tag '更新', :type => :button, :id => :update_calculator, :class => "btn" %>
</div><!-- series_calculator_properties -->


<div class="controls_row">
<%= submit_tag '更新', :class => 'btn' %>
<%= button_tag raw('<i class="icon-plus"></i> 計算系列の追加'), :type => :button, :id => :add_expression, :class => "btn" %>
<%= button_tag raw('<i class="icon-arrow-up"></i>'), :type => :button, :id => :move_up, :class => "btn" %>
<%= button_tag raw('<i class="icon-arrow-down"></i>'), :type => :button, :id => :move_down, :class => "btn" %>
</div>

<% end -%>
</div><!-- dialog_group -->

app/views/series_collections/edit.html.erb
<h1>テーブルを編集する</h1>

<%= render 'form' %>

<%= link_to 'Back', login_series_collection_show_path(id: @series_collection.id, login: @series_collection.user.login) %>

<%= javascript_include_tag 'series_collections' -%>

app/views/series_collections/index.html.erb
<h1>Tables</h1>

<%= paginate @series_collections %>

<table class="table table-condensed">
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Updated at</th>
  </tr>

  <%= render partial: 'index_row', collection: @series_collections -%>

</table>

<%= paginate @series_collections %>

app/views/series_collections/new.html.erb
<h1>新しいテーブルを作成する</h1>

<%= render 'form' %>

<%= javascript_include_tag 'series_collections' -%>

app/views/series_collections/show.html.erb
<div class="clearfix">
<div class="pull-right">
<% if signed_in? && current_user.id == @series_collection.user_id -%>
<%= link_to '編集', edit_series_collection_path(@series_collection), class: 'btn' %>
<%= link_to '削除', @series_collection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<% end -%>
</div>
</div><!-- clearfix -->

<div class="page-header">
<h1>
  <%= @series_collection.name %>
  <% if @series_collection.locked -%>
  <i class="icon-lock" alt="非公開" title="非公開"></i>
  <% end -%>
</h1>
<p>
  <%= link_to raw('<i class="icon-user"></i> ' + h(@series_collection.user.profile.name_view)), login_member_home_path(login: @series_collection.user.login)  %>
|
  作成日 <%= l @series_collection.created_at, format: :short %>
|
  更新日 <%= l @series_collection.updated_at, format: :short %>
</p>
<%= render :partial => 'shared/sns_link', object: @series_collection, locals: {url: login_series_collection_show_url(login: @series_collection.user.login, id: @series_collection.id), name: @series_collection.name} %>
<%= render :partial => 'shared/desc', :locals => {:series => @series_collection, :series_type_for_desc => 'series_collections'} -%>
</div><!-- page-header -->

<%#= render :partial => 'shared/graph_area', :locals => {:series_type => 'series_collection', :series => @series_collection, :graph_config => @graph_config} %>
<%= render :partial => 'shared/graph_area', :locals => {:series_type => 'series_collection', :series => @series_collection} %>

<%= render :partial => 'series_collections/selector', :locals => {:series => @series_collection, :series_type => 'series_collection'} -%>

<%= render :partial => 'shared/table', :object => @series_table %>

<%= javascript_include_tag 'series_collections' %>
<%= javascript_include_tag 'graph_dialog' %>
<%= javascript_include_tag 'edit_series_collections' %>

<% content_for :owner_profile do %>
<%= render :partial => 'shared/owner', :object => @series_collection.user -%>
<% end %>