config/routes.rb
Charthub::Application.routes.draw do

  devise_for :users

  scope '/:login/' do
    match 'series' => 'members#series', :as => :login_series
    match 'series/:id' => 'series#show', :as => :login_series_show
    match 'series/:id/load' => 'series#load', :as => :login_series_load
    match 'tables' => 'members#series_collections', :as => :login_series_collections
    match 'tables/:id' => 'series_collections#show', :as => :login_series_collection_show
    match 'tables/:id/load' => 'series_collections#load', :as => :login_series_collections_load
    match 'graphs' => 'members#graphs', :as => :login_graphs
    match 'graphs/:id' => 'graphs#show', :as => :login_graph_show
    match 'graphs/:id/load' => 'graphs#load', :as => :login_graph_load
  end
  match 'series/:id/load' => 'series#load', :as => :series_load
  match 'series/:id/desc' => 'series#get_desc', :as => :series_get_desc, :via => :get
  match 'series/preview' => 'series#preview_values', :as => :series_preview_values, :via => :post
  match 'series/:id/values' => 'series#create_values', :as => :series_create_values, :via => :post
  match 'tables/:id/load' => 'series_collections#load', :as => :series_collections_load
  match 'tables/:id/desc' => 'series_collections#get_desc', :as => :series_collections_get_desc, :via => :get
  match 'graphs/:id/load' => 'graphs#load', :as => :graph_load
  match 'graphs/config_test_new' => 'graphs#config_test_new', :as => :graph_config_test_new, :via => :put
  match 'graphs/:id/config_test_edit' => 'graphs#config_test_edit', :as => :graph_config_test_edit, :via => :put
  match 'graphs/new_memo' => 'graphs#new_memo', :as => :graph_new_memo
  match 'graphs/:id/image' => 'graphs#image', :as => :graph_image
  match 'profile/edit' => 'profiles#edit_myself'
  match 'profile/update' => 'profiles#update_myself', :via => :put
  match 'series/:series_id/graphs/new' => 'graphs#new_for_series', :as => :series_graphs_new
  match 'tables/:series_collection_id/graphs/new' => 'graphs#new_for_series_collection', :as => :series_collection_graphs_new
  match 'tables/:id/series' => 'series_collections#get_series', :via => :get
  match 'tables/:id/collection' => 'series_collections#get_selected_rows', :as => 'series_collection_collection', :via => :get
  match 'tables/:id/collection' => 'series_collections#update_collection', :as => 'update_series_collection_collection', :via => :put
  match 'config/index' => 'config#index', :as => 'config_index', :via => :get

  resources :series do
    resources :values
  end
  resources :profiles
  resources :series_orders
  resources :series_collections, :path => '/tables'
  resources :series_filters
  resources :graphs

  match '/home' => 'home#show', :as => :login_home
  match ':login/' => 'members#show', :as => :login_member_home

  root :to => 'top#index'

end

app/views/shared/_cell.html.erb
<% if cell.col_properties[:view_option].nil? || cell.col_properties[:view_option].selected == true -%>
<td class="table_value">
  <% if cell.blank? || cell.value_is_nil? -%>
  <% else -%>
    <%= cell.value %>
  <% end -%>
</td>
<% end -%>

app/views/shared/_desc.html.erb
<div id="series_desc_area" class="well well-small">
  <div><b>Description:</b></div>
  <div id="series_desc">
    <p id="series_desc_text"><%= auto_link( safe_text(series.description), html: {target: '_blank'} ) %></p>
    <% if signed_in_and_yours?(series.user_id) -%>
    <div><%= button_tag '編集', :id => 'series_desc_edit_button', class: 'btn' %></div>
    <% end -%>
  </div><!-- series_desc -->
  <div id="series_desc_update_form">
    <%= form_for( series, :url => {:controller => series_type_for_desc, :action => :update, :id => series.id, :format => :json}, :remote => true, :html => {id: :edit_desc_form}) do |f| -%>
      <%= f.text_area :description, :class => 'span6', :rows => 10 %>
      <div><%= f.submit '更新', class: 'btn' -%> <%= button_tag 'キャンセル', :id => :edit_description_cancel, class: 'btn', :type => 'button' %></div>
    <% end -%>
  </div><!-- series_desc_update_form -->
</div><!-- series_desc_area -->

<%= hidden_field_tag :series_type_for_desc, series_type_for_desc, :id => 'series_type_for_desc' -%>

<%= javascript_include_tag 'edit_desc' -%>

app/views/shared/_error_message.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this graph from being saved:</h2>

    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_graph_area.html.erb
<div id="graph_area">
<div class="well well-small">

<% if series.graphs.size > 0 -%>
<ul class="thumbnails">
  <%= render :partial => 'shared/graph_thumbnail', :collection => series.graphs %>
</ul><!-- thumbnails -->
<% end -%>

  <% if signed_in_and_yours?(series.user_id) -%>
    <% if series_type == 'series' -%>
      <%= link_to raw('<i class="icon-plus"></i> グラフを追加'), series_graphs_new_path(series_id: series.id), :class => 'btn btn-primary' %>
    <% elsif series_type == 'series_collection' -%>
      <%= link_to raw('<i class="icon-plus"></i> グラフを追加'), series_collection_graphs_new_path(series_collection_id: series.id), :class => 'btn btn-primary' %>
    <% end -%>
  <% end -%>

</div><!-- well -->

<% child_graphs = series.child_graphs -%>
<% if child_graphs.size > 0 -%>
<div class="well well-small">
<div id="child_graphs_headline">
<span id="child_graphs_toggle"><i class="toggle-chevron icon-chevron-right"></i><i class="toggle-chevron icon-chevron-down"></i></span> 子系列のグラフ（<span id="child_graphs_count"><%= child_graphs.size %>件</span>）
</div>
<%# if series_type == 'series_collection' -%>
<ul id="child_graphs_thumbs" class="thumbnails">
  <%= render :partial => 'shared/graph_thumbnail', :collection => series.child_graphs %>
</ul><!-- thumbnails -->
<%# end -%>
</div><!-- well -->
<% end # if child_graphs.size > 0 -%>

<%= render partial: 'shared/graph_dialog_area', locals: {series: series, mode: :graph_area} -%>

</div><!-- graph_area -->

app/views/shared/_graph_url_bar.html.erb
<div class="controls_row">
  <div class="input-append">
  <%= text_field_tag :graph_url, '', :id => 'graph_url', class: 'input-xlarge' %>
  <%= button_tag '表示', :type => 'button', :id => 'show_graph', :class => 'btn' %>
  </div><!-- input-append -->
</div><!-- controls_row -->

app/views/shared/_head.html.erb
<% if head[:series_type] == 'substantial' -%>
<%# 実系列の場合 -%>

<% if head[:view_option].nil? || head[:view_option].selected == true -%>
<th class="table_value">
<div>

<%# 系列の名前 -%>
<% if head[:source].series_is_deleted? -%>
<%= head[:source].name -%>
<% else -%>
<%= link_to head[:source].name, login_series_show_path(login: head[:source].series.user.login, id: head[:source].series_id), :title => head[:source].series.name -%>
<% end -%>

</div>

<%# 単位の表示 -%>
<% if !head[:source].series_is_deleted? && !head[:source].series.unit.blank? -%>
<div><%= head[:source].series.unit.blank? ? "" : "(" + head[:source].series.unit + ")" %></div>
<% end -%>

</th>
<% end -%>

<% elsif head[:series_type] == 'calcuration' -%>
<%# 計算系列の場合 -%>

<% if head[:view_option].nil? || head[:view_option].selected == true -%>
<th class="table_value">
<span title="<%= head[:source].expression %>"><%= head[:source].name %></span>
</th>
<% end -%>

<% end -%>

app/views/shared/_own_series.html.erb
<tr>
<td><%= own_series.series_type_to_str({'series' => 'origin', 'series_filter' => 'filtered'}) %></td>
<td>
  <%= link_to own_series.name, login_series_show_path(:login => own_series.user.login, :id => own_series.id) %>
  <% if own_series.locked -%>
  <i class="icon-lock" alt="非公開" title="非公開"></i>
  <% end -%>
</td>
<td><%= l own_series[date_type], format: :short %></td>
</tr>

app/views/shared/_own_series_collections.html.erb
<tr>
<td>
  <%= link_to own_series_collections.name, :controller => :series_collections, :action => :show, :id => own_series_collections.id %>
  <% if own_series_collections.locked -%>
  <i class="icon-lock" alt="非公開" title="非公開"></i>
  <% end -%>
</td>
<td><%= l own_series_collections[date_type], format: :short %></td>
</tr>

app/views/shared/_owner.html.erb
<div id="sidebar_owner" class="well well-small sidebar-nav">
  <div class="name">
  
  <%= link_to owner.profile.name_view, login_member_home_path(login: owner.login) %>
  <% unless owner.profile.twitter_account.blank? -%>
  <%= link_to image_tag('/assets/Twitter_logo_blue_100.png', width: '12px'), 'https://twitter.com/' + owner.profile.twitter_account, target: '_blank' %>
  <% end -%>
  </div>
  <div class="introduction">
  <%= safe_text(owner.profile.introduction) %>
  </div>
  <div class="home_shortcut clearfix">
    <div class="home_shortcut_tip pull-left">
      <div><%= link_to '系列', login_series_path(login: owner.login) %></div>
      <div><%= link_to "(#{owner.series_count})", login_series_path(login: owner.login) %></div>
    </div>
    <div class="home_shortcut_tip pull-left">
      <div><%= link_to 'テーブル', login_series_collections_path(login: owner.login) %></div>
      <div><%= link_to "(#{owner.series_collections_count})", login_series_collections_path(login: owner.login) %></div>
    </div>
    <div class="home_shortcut_tip pull-left">
      <div><%= link_to 'グラフ', login_graphs_path(login: owner.login) %></div>
      <div><%= link_to "(#{owner.graphs_count})", login_graphs_path(login: owner.login) %></div>
    </div>
  </div>
</div>

app/views/shared/_row.html.erb
<tr>
<td class="table_number"><%= row_counter + 1 -%></td>
<td class="span1"><%= row[1].label %></td>
<%= render :partial => 'shared/cell', :collection => row[1].cells %>
<td></td>
</tr>

app/views/shared/_select_status.html.erb
<div id="select_status" class="clearfix">
  <div class="select_status_title pull-left">選択範囲</div>
  <div class="select_status_content">
    <% if graph.value_select_mode == 1 -%>
    <%= graph.select_from -%> から <%= graph.select_to -%> 
    <% elsif graph.value_select_mode == 2 -%>
    <%= graph.select_choice.join(',') -%> 
    <% end -%>
  </div>
</div>

app/views/shared/_sns_link.html.erb
<div>
<a href="https://twitter.com/share" class="twitter-share-button" data-text="<%= name %>" data-url="<%= url %>" <%= raw 'data-via="' + h(sns_link.user.profile.twitter_account) + '"' if !sns_link.user.profile.twitter_account.blank? && sns_link.user.profile.include_twitter_account %> data-hashtags="graphshare">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>

app/views/shared/_sns_metadata.html.erb
<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@graphshare_jp">
<% unless graph.user.profile.twitter_account.blank? -%>
<meta name="twitter:creator" content="@<%= graph.user.profile.twitter_account %>">
<% end -%>
<meta name="twitter:title" content="<%= graph.title -%>">
<meta name="twitter:description" content="<%= graph.graphable.description %>">
<meta name="twitter:image:src" content="http://charthub.526s.net<%= graph_image_path(id: graph.id) %>">

app/views/shared/_table.html.erb
<div class="table_area">
<table class="table table-condensed">
<tr>
<th class="table_number">No</th>
<th class="table_label">ラベル</th>
<%= render :partial => 'shared/head', :collection => table.col_properties %>
<th></th>
</tr>
<%= render :partial => 'shared/row', :collection => table.rows %>
</table>
</div><!-- table_area -->