config/routes.rb
Charthub::Application.routes.draw do

  devise_for :users

  scope '/:login/' do
    match 'series' => 'members#series', :as => :login_series
    match 'series/:id' => 'series#show', :as => :login_series_show
    match 'series/:id/load' => 'series#load', :as => :login_series_load
    match 'tables' => 'members#series_collections', :as => :login_series_collections
    match 'tables/:id' => 'series_collections#show', :as => :login_series_collection_show
    match 'tables/:id/load' => 'series_collections#load', :as => :login_series_collections_load
    match 'graphs' => 'members#graphs', :as => :login_graphs
    match 'graphs/:id' => 'graphs#show', :as => :login_graph_show
    match 'graphs/:id/load' => 'graphs#load', :as => :login_graph_load
  end
  match 'series/:id/load' => 'series#load', :as => :series_load
  match 'series/:id/desc' => 'series#get_desc', :as => :series_get_desc, :via => :get
  match 'series/preview' => 'series#preview_values', :as => :series_preview_values, :via => :post
  match 'series/:id/values' => 'series#create_values', :as => :series_create_values, :via => :post
  match 'tables/:id/load' => 'series_collections#load', :as => :series_collections_load
  match 'tables/:id/desc' => 'series_collections#get_desc', :as => :series_collections_get_desc, :via => :get
  match 'graphs/:id/load' => 'graphs#load', :as => :graph_load
  match 'graphs/config_test_new' => 'graphs#config_test_new', :as => :graph_config_test_new, :via => :put
  match 'graphs/:id/config_test_edit' => 'graphs#config_test_edit', :as => :graph_config_test_edit, :via => :put
  match 'graphs/new_memo' => 'graphs#new_memo', :as => :graph_new_memo
  match 'graphs/:id/image' => 'graphs#image', :as => :graph_image
  match 'profile/edit' => 'profiles#edit_myself'
  match 'profile/update' => 'profiles#update_myself', :via => :put
  match 'series/:series_id/graphs/new' => 'graphs#new_for_series', :as => :series_graphs_new
  match 'tables/:series_collection_id/graphs/new' => 'graphs#new_for_series_collection', :as => :series_collection_graphs_new
  match 'tables/:id/series' => 'series_collections#get_series', :via => :get
  match 'tables/:id/collection' => 'series_collections#get_selected_rows', :as => 'series_collection_collection', :via => :get
  match 'tables/:id/collection' => 'series_collections#update_collection', :as => 'update_series_collection_collection', :via => :put
  match 'config/index' => 'config#index', :as => 'config_index', :via => :get

  resources :series do
    resources :values
  end
  resources :profiles
  resources :series_orders
  resources :series_collections, :path => '/tables'
  resources :series_filters
  resources :graphs

  match '/home' => 'home#show', :as => :login_home
  match ':login/' => 'members#show', :as => :login_member_home

  root :to => 'top#index'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show, :load, :get_desc]
  before_filter :check_exist, only: [:show, :load, :get_desc]
  #before_filter :check_permission, except: [:index, :show, :new, :create, :load, :get_desc]
  before_filter :check_permission, only: [:edit, :update, :destroy, :create_values]

  # GET /series
  # GET /series.json
  def index
    @series = Kaminari.paginate_array(Series.includes(:user).order('updated_at DESC'))
    @series = @series.page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1
  # GET /series/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/new
  # GET /series/new.json
  def new
    @series = Series.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @series }
    end
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(params[:series])
    @series.user_id = current_user.id
    #@series.series_type = 'series' # series_type自体不要となったはずなので後々DBから削除予定。2014-12-06

    respond_to do |format|
      if @series.save
        #format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.html { redirect_to login_series_show_path(login: @series.user.login, id: @series.id), notice: 'Series was successfully created.' }
        format.json { render json: @series, status: :created, location: @series }
      else
        format.html { render action: "new" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /series/1
  # PUT /series/1.json
  def update

    #万が一、パラメータに故意に挿入された場合を想定して削除。
    params[:series].delete('category_axis_type')

    respond_to do |format|
      if @series.update_attributes(params[:series])
        format.html { redirect_to login_series_show_path(login: @series.user.login, id: @series.id), notice: 'Series was successfully updated.' }
        #format.json { head :no_content }
        format.json { render json: @series, status: :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  # TODO: valuesも含めて削除されるようにすること。 DONE
  # TODO: テーブルに含まれる等の情報を事前に出す？
  def destroy
    login = @series.user.login
    if @series.is_filter
    else 
      @series.values.clear
    end
    @series.graphs.clear
    @series.destroy # series_filtersは:dependentで削除される。

    respond_to do |format|
      # TODO: リダイレクト先を変える（HOMEの系列等？） DONE
      #format.html { redirect_to series_index_url }
      format.html { redirect_to login_home_path }
      format.json { head :no_content }
    end
  end

  # 値を更新
  def create_values

    #@series = Series.find(params[:id].to_i, :include => [:values])

    ActiveRecord::Base.transaction do

      @series.values.destroy_all
      @series.create_values_by_text(params[:values_by_text], params[:delimitter])
      @series.updated_at = Time.now
      @series.save!

    end #transaction

    respond_to do |format|
      format.html { redirect_to login_series_show_path(:login => current_user.login, :id => @series.id), notice: 'Value was successfully created.' }
#      format.json { render json: @value, status: :created, location: @value }
    end

  rescue ActiveRecord::RecordInvalid => e

    @series = Series.find(params[:id].to_i, :include => [:values])

    respond_to do |format|
      format.html { render action: "show" }
      format.json { render json: @value.errors, status: :unprocessable_entity }
    end

  end

  def load

    #@series = Series.find(params[:id])

    # デフォルト値をセット
    @graph_config = MyLib::MyCcchartConfig.default_to_chart
    @graph_config[:title] = @series.name

    render json: {data: @series.to_json_for_chart, config: @graph_config, status: 200}
=begin
    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { render json: @series.to_json_for_chart }
    end
=end

  end

  # 詳細画面でdescriptionをAjaxで取得する。
  def get_desc

    renderd = view_context.safe_text(@series.description)

    render text: renderd

  end

  # フォームから受け取ったテキストをパースして値を検証する。
  def preview_values

    data = Hash.new
    if params[:series_id].blank?
      series = Series.new 
    else
      series = Series.find(params[:series_id])
    end

    begin
      values = series.build_values_by_text(params[:values_by_text], params[:delimitter])    
      html = render_to_string partial: 'series/table', object: series, locals: {values: values}
      data[:html] = html
      render json: data
    rescue MyException::MyParsingError => ex
      html = ex.message.split("\n").map{|line|
        ERB::Util.h(line)
      }.join('</br>')
      render text: html, status: 400 
    rescue => ex
      logger.error("#{ex.message}\n#{ex.backtrace}")
      html = "ERROR"
      render text: html, status: 400 
    end

  end

private

end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%#= form_for(@series, :url =>{:controller => @series_type.pluralize, :action => :create}, :html => {:id => 'series_config_form', :class => 'form-horizontal'}, :method => :post) do |f| %>
<%= form_for(@series, :html => {:id => 'series_config_form', :class => 'form-horizontal'}) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%#= f.hidden_field :series_type #元々フィルタ以外の系列もあることを想定していたが今は必要ないはずなので後で削除 2014-12-06 -%>
  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :unit, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :unit %>
    </div>
  </div>

<% if @series.id.blank? -%>
  <div class="control-group">
    <%= f.label :category_axis_type, :class => "control-label" %>
    <div class="controls">
    <%= f.select :category_axis_type, options_for_select(MY_APP['category_axis_type'].map{|key,val| [val,key] }) %>
    </div>
  </div>
<% else -%>
  <div class="control-group">
    <%= f.label :category_axis_type, :class => "control-label" %>
    <div class="controls">
    <%= MY_APP['category_axis_type'][@series.category_axis_type] %>
    </div>
  </div>
<% end -%>
  <div class="control-group">
    <%= f.label :category_axis_unit, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :category_axis_unit, class: 'input-mini' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :round_digit, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :round_digit, :type => 'number', :class => 'input-mini' %>
    </div>
  </div>
<% if false -%>
  <div class="control-group">
    <%= f.label :locked, :class => "control-label" %>
    <div class="controls">
    <%= f.check_box :locked %>
    </div>
  </div>
<% end -%>
  <div class="control-group">
    <%= f.label :description, :class => "control-label" %>
    <div class="controls">
    <%= f.text_area :description, :size => 5, :rows => 10, :style => 'width:300px;' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
    <%= f.submit class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/series/_gconf.html.erb
<div class="control-group">
  <%= label_tag :title, 'タイトル', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :title, gconf[:title] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :width, '幅', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :width, gconf[:width] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :height, '高さ', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :height, gconf[:height] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :axis_x_width, 'X軸幅', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :axis_x_width, gconf[:axisXWidth] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :axis_x_len, 'X軸目盛本数', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :axis_x_len, gconf[:axisXLen] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :axis_y_width, 'Y軸幅', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :axis_y_width, gconf[:axisYWidth] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :axis_y_len, 'Y軸目盛本数', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :axis_y_len, gconf[:axisYLen] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :only_chart, 'チャートのみ表示', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :only_chart, gconf[:onlyChart] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :only_chart_width_title, 'チャートとタイトルのみ表示', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :only_chart_width_title, gconf[:onlyChartWidthTitle] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :padding_top, '上部余白', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :padding_top, gconf[:paddingTop] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :padding_bottom, '下部余白', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :padding_bottom, gconf[:paddingBottom] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :padding_left, '左余白', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :padding_left, gconf[:paddingLeft] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :padding_right, '右部余白', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :padding_right, gconf[:paddingRight] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :x_color, 'X軸の色', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :x_color, gconf[:xColor] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :y_color, 'Y軸の色', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :y_color, gconf[:yColor] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :x_scale_skip, 'X軸スキップ', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :x_scale_skip, gconf[:xScaleSkip] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :y_scale_skip, 'Y軸スキップ', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :y_scale_skip, gconf[:yScaleSkip] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :x_scale_rotate, 'X軸回転', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :x_scale_rotate, gconf[:xScaleRotate] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :y_scale_rotate, 'Y軸回転', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :y_scale_rotate, gconf[:yScaleRotate] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :use_val, 'チャートに値を表示', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :use_val, gconf[:useVal] %>
  </div>
</div>
<div class="control-group">
  <%= label_tag :use_marker, 'マーカーを表示', :class => "control-label" %>
  <div class="controls">
  <%= text_field_tag :use_marker, gconf[:useMarker] %>
  </div>
</div>

app/views/series/_index_row.html.erb
  <tr>
    <td>
      <%= link_to index_row.user.profile.name_view, login_member_home_path(login: index_row.user.login) %>
    </td>
    <td>
      <%= index_row.is_filter_to_str('filtered','origin') %>
    </td>
    <td><%= link_to index_row.name, login_series_show_path(login: index_row.user.login, id: index_row.id) %></td>
    <td><%= l index_row.updated_at, format: :short %></td>
  </tr>

app/views/series/_row.html.erb
<tr>
  <td class="table_number"><%= row_counter + 1 -%></td>
  <td class="span2"><%= row.label -%></td>
  <td class="table_value"><%= !row.value.blank? ? number_with_precision(row.value, :precision => round_digit) : '' -%></td>
  <td><%= row.note -%></td>
</tr>

app/views/series/_table.html.erb
<div class="table_area">
<table class="table table-condensed">
<thead>
<tr>
  <th>No</th>
  <th>ラベル<%= table.category_axis_unit.blank? ? "" : "(#{table.category_axis_unit})" %></th>
  <th>値<%= table.unit.blank? ? "" : "(" + table.unit + ")" %></th>
  <th>備考</th>
</tr>
</thead>
<tbody>
<%= render :partial => 'series/row', :collection => values, :locals => {:round_digit => table.round_digit} -%>
</tbody>
</table>
</div><!-- table_area -->

app/views/series/edit.html.erb
<h1>系列を編集する</h1>

<%= render 'form' %>

<%= link_to 'Back', login_series_show_path(id: @series.id, login: current_user.login) %>

app/views/series/index.html.erb
<h1>Series</h1>

<%= paginate @series %>

<table class="table table-condensed">
  <tr>
    <th>User</th>
    <th>Type</th>
    <th>Name</th>
    <th>Updated at</th>
  </tr>

  <%= render partial: 'index_row', collection: @series %>

</table>

<%= paginate @series %>

app/views/series/new.html.erb
<h1>新しい系列を作成する</h1>

<%= render 'form' %>

app/views/series/show.html.erb
<div class="clearfix">
<div class="pull-right">
<% if signed_in? && current_user.id == @series.user_id -%>
<% if @series.is_filter -%>
<%= link_to '編集', edit_series_filter_path(@series), class: 'btn' %>
<% else -%>
<%= link_to '編集', edit_series_path(@series), class: 'btn' %>
<% end -%>
<%= link_to '削除', @series, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<% end -%>
</div>
</div><!-- clearfix -->

<div class="page-header">
<h1>
<%= @series.name %>
<% if @series.locked -%>
<i class="icon-lock" alt="非公開" title="非公開"></i>
<% end -%>
</h1>
<p>
  <%= link_to raw('<i class="icon-user"></i> ' + h(@series.user.profile.name_view)), login_member_home_path(login: @series.user.login)  %>

|
  作成日 <%= l @series.created_at, format: :short %>
|
  更新日 <%= l @series.updated_at, format: :short %>
  <% if @series.is_filter -%>
|
 <i class="icon-th-list"></i> 元の系列： <%= link_to "#{@series.filter_target.name}", login_series_show_path(id: @series.filter_target.id, login: @series.filter_target.user.login) %>
  <% end -%>
</p>
<%= render :partial => 'shared/sns_link', object: @series, locals: {url: login_series_show_url(login: @series.user.login, id: @series.id), name: @series.name} %>
<%= render :partial => 'shared/desc', :locals => {:series => @series, :series_type_for_desc => 'series'} -%>
</div><!-- page-header -->

<%= render :partial => 'shared/graph_area', :locals => {:series_type => 'series', :series => @series, :graph_config => @graph_config} %>

<% if signed_in_and_yours?(@series.user_id) -%>
<% unless @series.is_filter -%>
<ul class="nav nav-tabs">
  <li class="active" onclick="showEditSeriesDialog();">
    <a>編集</a>
  </li>
</ul><!-- nav-tabs -->
<%#= button_tag '編集', :type => 'button', :id => 'edit_series_button', :class => "btn", :onclick => "showEditSeriesDialog()" %>
<% end #unless -%>
<% end #if -%>
<div class="row">

  <div id="edit_series_dialog" class="span3">
<% if signed_in_and_yours?(@series.user_id) -%>
<% unless @series.is_filter -%>
<%= form_tag({:controller => :values, :series_id => @series.id, :action => :create}, id: :edit_series_form ) do  -%>

  <%= hidden_field_tag :series_id, @series.id, id: :series_id -%>

  <div class="controls_row">
  <%= button_tag '送信', :type => :submit, :class => "btn" -%>
  <%= button_tag 'プレビュー', :type => :button, :id => "preview_values", :class => "btn" -%>
  <%= button_tag '閉じる', :type => 'button', :id => 'close_series_button', :class => "btn", :onclick => "hideEditSeriesDialog()" %>
  </div>

  <div>
  区切り: <%= select_tag :delimitter, options_for_select({"カンマ(,)" => "comma", "タブ" => "tab"}), :style => "width:100px" %>
  </div>

  <div class="controls_row">
  項目軸種別: <%= MY_APP['category_axis_type'][@series.category_axis_type] %>
  </div>

  <div>
  <%= text_area_tag :values_by_text, @series.to_csv, :style => "width:100%;height:300px" -%>
  </div>
<% end #form_tag -%>
<% end #unless -%>
<% end #signed_in? -%>
  </div><!-- span -->

  <div id="series_table_area" class="span6">
<%= render :partial => 'table', :object => @series, :locals => {:values => @series.values} -%>
  </div><!-- series_table_area -->

</div><!-- row -->

<div id="preview_values_dialog" title="プレビュー">
  <div class="controls_row">
    <%= button_tag '更新', id: :commit_values, class: 'btn btn-primary' -%>
  </div>
<div id="preview_values_dialog_content">
</div>
</div><!-- preview_values_dialog -->

<%= javascript_include_tag 'series' %>
<%= javascript_include_tag 'graph_dialog' %>
<%= javascript_include_tag 'edit_series_collections' %>

<% content_for :owner_profile do %>
<%= render :partial => 'shared/owner', :object => @series.user -%>
<% end %>