config/routes.rb
Charthub::Application.routes.draw do

  devise_for :users

  scope '/:login/' do
    match 'series' => 'members#series', :as => :login_series
    match 'series/:id' => 'series#show', :as => :login_series_show
    match 'series/:id/load' => 'series#load', :as => :login_series_load
    match 'tables' => 'members#series_collections', :as => :login_series_collections
    match 'tables/:id' => 'series_collections#show', :as => :login_series_collection_show
    match 'tables/:id/load' => 'series_collections#load', :as => :login_series_collections_load
    match 'graphs' => 'members#graphs', :as => :login_graphs
    match 'graphs/:id' => 'graphs#show', :as => :login_graph_show
    match 'graphs/:id/load' => 'graphs#load', :as => :login_graph_load
  end
  match 'series/:id/load' => 'series#load', :as => :series_load
  match 'series/:id/desc' => 'series#get_desc', :as => :series_get_desc, :via => :get
  match 'series/preview' => 'series#preview_values', :as => :series_preview_values, :via => :post
  match 'series/:id/values' => 'series#create_values', :as => :series_create_values, :via => :post
  match 'tables/:id/load' => 'series_collections#load', :as => :series_collections_load
  match 'tables/:id/desc' => 'series_collections#get_desc', :as => :series_collections_get_desc, :via => :get
  match 'graphs/:id/load' => 'graphs#load', :as => :graph_load
  match 'graphs/config_test_new' => 'graphs#config_test_new', :as => :graph_config_test_new, :via => :put
  match 'graphs/:id/config_test_edit' => 'graphs#config_test_edit', :as => :graph_config_test_edit, :via => :put
  match 'graphs/new_memo' => 'graphs#new_memo', :as => :graph_new_memo
  match 'graphs/:id/image' => 'graphs#image', :as => :graph_image
  match 'profile/edit' => 'profiles#edit_myself'
  match 'profile/update' => 'profiles#update_myself', :via => :put
  match 'series/:series_id/graphs/new' => 'graphs#new_for_series', :as => :series_graphs_new
  match 'tables/:series_collection_id/graphs/new' => 'graphs#new_for_series_collection', :as => :series_collection_graphs_new
  match 'tables/:id/series' => 'series_collections#get_series', :via => :get
  match 'tables/:id/collection' => 'series_collections#get_selected_rows', :as => 'series_collection_collection', :via => :get
  match 'tables/:id/collection' => 'series_collections#update_collection', :as => 'update_series_collection_collection', :via => :put
  match 'config/index' => 'config#index', :as => 'config_index', :via => :get

  resources :series do
    resources :values
  end
  resources :profiles
  resources :series_orders
  resources :series_collections, :path => '/tables'
  resources :series_filters
  resources :graphs

  match '/home' => 'home#show', :as => :login_home
  match ':login/' => 'members#show', :as => :login_member_home

  root :to => 'top#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- For SNS -->
    <%= yield :sns_metadata -%>

    <title><%= content_for?(:title) ? yield(:title) : "graphshare" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.js"></script>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">graphshare</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">

          <% if user_signed_in? -%>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Action<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to '新しい系列を作る', new_series_path %></li>
                <li><%= link_to '新しい系列フィルターを作る', new_series_filter_path %></li>
                <li><%= link_to '新しいテーブルを作る', new_series_collection_path %></li>
              </ul>
            </li>
            <li><%= link_to "Profile", "/profile/edit"  %></li>
            <li><%= link_to "Config", "/config/index"  %></li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
          <% else -%>
            <li>
              <%= link_to('Login', new_user_session_path)  %>  
            </li>
<% if MY_APP['signup_enabled'] -%>
            <li>
              <%= link_to "Sign up", '/users/sign_up' -%>
            </li>
<% end -%>

          <% end -%>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <!-- <div class="container-fluid"> -->
    <div class="container">
      <!-- <div class="row-fluid"> -->
      <div class="row">
        <div class="span3">

          <%= yield :owner_profile %>

          <div class="well well-small sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "系列", series_index_path  %></li>
              <li><%= link_to "テーブル", series_collections_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>

          <%= yield %>

        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; graphshare 2014</p>
      </footer>

    </div> <!-- /container -->

<!-- global template -->
<div id="notify_message">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <div id="notify_message_text"></div>
</div>

<% if ENV['RAILS_ENV'] == 'production' -%>
<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5585435-6', 'auto');
  ga('send', 'pageview');

</script>
<% end -%>

<!-- for getStrWidth -->
<span id="ruler" style="visibility:hidden;position:absolute;white-space:nowrap;">&nbsp;</span>

  </body>
</html>